### ISSUE TITLE
APInt dialect draft

### ISSUE THREAD

**Issue by 7FM** [7FM/circt#1]

**Comment by 7FM** [comment]
@jopperm shall I add some tests for [apint](https://github.com/7FM/circt/tree/feature/apint_dialect)?
Any other wishes or do you think that's enough to submit the draft?

**Comment by jopperm** [comment]
Yes, tests are definitely required, to provide at least some examples for the assembler format. Thanks!

**Comment by 7FM** [comment]
I am getting `unexpected error: 'arith.constant' op integer return type must be signless` for smth. like `%c1_0 = arith.constant 0 : ui1`.
Do you know of a dialect that supports storing the signedness info or do I need to define a custom constant Op?

**Comment by jopperm** [comment]
Define `apint.constant`, you wouldn't want to depend on another dialect just for its constant-like operation.

**Comment by 7FM** [comment]
[apint.constant](https://github.com/7FM/circt/blob/8b3e4f68439ca226008e447fda4bb7142fe3c441/include/circt/Dialect/APInt/APIntOps.td#L49)
[tests](https://github.com/7FM/circt/tree/feature/apint_dialect/test/Dialect/APInt)
From my point of view, it should be ready. Or did I missed something?

**Comment by 7FM** [comment]
see [PR](https://github.com/llvm/circt/pull/2242)
